### ISSUE TITLE
requirements 

### ISSUE THREAD

**Issue by rusnuker** [ebankoff/BoMbEr#1]
Hey. Can anyone here build full installation instruction/script? I don't know what i should install on my Termux for make the script work.

**Comment by HuErGa** [comment]
*Hi*


step 1.


First you need to install git if you don't have it.


step 2.


Then install python


step 3.


Then follow the instructions


git clone https://github.com/HuErGa/BoMbEr

cd BoMbEr

python3 BoMbEr.py


If the program doesn’t start, then you don’t have the required libraries.
The error will indicate which library you don’t have. Enter into the
console: pip install your library



Вт, 27 апр. 2021 г. в 10:12, rusnuker ***@***.***>:

**Comment by rusnuker** [comment]
you are genius
i wrote because i cannot install libraries

**Comment by evil-monti** [comment]
Hey, I installed library(pip install library), but script not working. 
Error. No module named 'telebot'.

**Comment by HuErGa** [comment]
Hi

Are you sure you installed the library correctly?

first check if pip is installed, then:

step1
pip uninstall telebot

step2
pip install pyTelegramBotAPI

Чт, 29 апр. 2021 г. в 08:54, evil-monti ***@***.***>:

**Comment by evil-monti** [comment]
thx sir, script working

**Comment by vectorlol** [comment]
Hi, I did requirements.txt file specially for this repo. Follow the instructions below.

First of all download requirements.txt from gdrive: 

https://drive.google.com/file/d/1aUGCZZZ8UpiN_nJUy4w9q3lhze3wD5wf/view?usp=drivesdk 

! check it's path, if it isn't in Download folder, you can move file there, or you can change the path in command, which will be below. 

then open termux and write: 

pkg update -y && pkg update -y 

pkg install git python 

/data/data/com.termux/files/usr/bin/python3 -m pip install --upgrade pip 

git clone https://github.com/HuErGa/BoMbEr 

cp /storage/emulated/0/Download/requirements.txt /data/data/com.termux/files/home/BoMbEr 

cd BoMbEr 

pip install -r requirements.txt 

python3 BoMbEr.py
