### ISSUE TITLE
chrome driver

### ISSUE THREAD

**Issue by bloboxidate** [ebankoff/BoMbEr#12]
i have the latest chrome driver and chrome virsion but it still tells me i need to update my chrome driver to the latest virsion

**Comment by ebankoff** [comment]
> i have the latest chrome driver and chrome virsion but it still tells me i need to update my chrome driver to the latest virsion
> 
> 

Hello, please send a screenshot of the error. This will make it easier for me to understand how to help you

**Comment by bloboxidate** [comment]
![Uploading image.jpg…]()

**Comment by bloboxidate** [comment]
![Uploading 4DFE8380-83E8-4179-87BF-763BA2922F55.jpeg…]()

**Comment by bloboxidate** [comment]
[Screenshot.pdf](https://github.com/ebankoff/BoMbEr/files/7675744/Screenshot.pdf)

**Comment by ebankoff** [comment]
You provided a link to the account, but you just have to enter his name
![Screenshot_1](https://user-images.githubusercontent.com/80776324/145203763-763b724b-c17e-4b7d-bb66-0cc8ecdb9f02.png)

**Comment by ebankoff** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/80776324/145204271-c82e5d20-7eba-4493-9e21-b42c323becfe.png)

**Comment by bloboxidate** [comment]
I have done exactly as the photo above and i still get the same error

**Comment by ebankoff** [comment]
So try the following:
* Reinstall google chrome
* Reinstall BoMbEr
* Uninstall chrome drive (BoMbEr will install the right one)

If this does not help you, try to install BoMbEr like this: **pip install ebankoff-bomber** 
Run it like this: **BoMbEr**

**Comment by bloboxidate** [comment]
followed all the steps the problem is still there

**Comment by Oldlexar** [comment]
same shit

**Comment by Oldlexar** [comment]
fix that

**Comment by ebankoff** [comment]
The problem seems to be on your side, because I did not find any errors in the program. Download and run this version of BoMbEr: [click](https://sharemods.com/rczgsqo5md1i/BoMbEr_debug.rar.html) and send me a screenshot of the error. This will help me figure out how to help you.

**Comment by bloboxidate** [comment]
![Uploading image.jpg…]()

**Comment by bloboxidate** [comment]
![image](https://user-images.githubusercontent.com/94928162/145653690-238c2397-b605-4638-99bd-71c088a9c845.jpg)

**Comment by ebankoff** [comment]
Try this: [click](https://sharemods.com/qt208hix87a4/BoMbEr_debug.rar.html) I added something there, maybe it will help you

**Comment by bloboxidate** [comment]
![image](https://user-images.githubusercontent.com/94928162/145655089-fa7585f4-f537-45d0-b917-42ded3b6b386.jpg)

**Comment by ebankoff** [comment]
You probably did something wrong. You should get an error on startup, not just the text "ERROR". In any case, try to install it: [click](https://sharemods.com/ubbm6yaaw1qi/BoMbEr_debug.rar.html) Run it and send me a screenshot of the error

**Comment by ebankoff** [comment]
**Before you download what I sent, delete the previous version of BoMbEr**

**Comment by bloboxidate** [comment]
![image](https://user-images.githubusercontent.com/94928162/146009398-5be7086d-7885-4d25-badf-e12b77cf743d.jpg)

**Comment by ebankoff** [comment]
Hi, I'm sorry I haven't responded for a while. I released a new version of BoMbEr, try to install it. If that doesn't help either, it's a problem on your end. BoMbEr might not work because you run it with python2 and it needs python3. That's all I can help you with.

**Good luck!**
