### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by Muhammad-Fiqri** [ebankoff/BoMbEr#14]
after typing pip install -r requirements.txt it said
"
ERROR: Could not find a version that satisfies the requirement sys (from versions: none)
ERROR: No matching distribution found for sys
"
![Untitled](https://user-images.githubusercontent.com/60091975/148544207-fba51f5e-83aa-4a99-afdb-a889a8db8f27.png)

**Comment by ebankoff** [comment]
**Fixed!**

**Comment by Muhammad-Fiqri** [comment]
Care to elaborate futher?

**Comment by ebankoff** [comment]
**Now you can reinstall the requirements.txt, there should be no errors**
