### ISSUE TITLE
SMS bomber doesn't work

### ISSUE THREAD

**Issue by gohoski** [ebankoff/BoMbEr#16]
I tried to bomb my two telephone numbers with no success. No SMS are being sent.
```
┏━━━┓┏━┓┏━┓┏━━━┓
┃┏━┓┃┃ ┗┛ ┃┃┏━┓┃
┃┗━━┫┃┏┓┏┓┃┃┗━━┫
┗━━┓┃┃┃┃┃┃┃┗━━┓┃
┃┗━┛┃┃┃┃┃┃┃┃┗━┛┃
┗━━━┛┗┛┗┛┗┛┗━━━┛

===============================
      Supported countries
           RU    BY
           KZ    UA
           US    UK
===============================

Proxy? yes/no: yes
Target country code: +7
Target number: 7*********7
Time attack(in seconds): 125
Number of threads(recommended - 10, max - 100): 15
[15] threads started

Attacking
===============================
            SUCCESS
===============================

Exit? yes/no:
```

**Comment by ebankoff** [comment]
Hello. At the moment spam works only for Ukrainian and Russian numbers.

**Comment by gohoski** [comment]
I did use a Russian number.

**Comment by ebankoff** [comment]
Then you installed or configured it incorrectly. It could also be a proxy problem. I recommend to try Telegram bot: **https://t.me/beast_bomberr_bot**, everything is already set up there and you only need to specify phone number for spam.

**Comment by gohoski** [comment]
I forgor 💀 to configure the proxies. Thank you for the help!

**Comment by gohoski** [comment]
Also, what type of proxies are needed? HTTP? HTTPS? SOCKS4?

**Comment by ebankoff** [comment]
use **http** proxy

**Comment by ebankoff** [comment]
I advise you to buy proxies here: **https://astroproxy.com**
