### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by GurteX** [ebankoff/BoMbEr#17]
Traceback (most recent call last):
  File "BoMbEr.py", line 60, in <module>
    import emoji
ModuleNotFoundError: No module named 'emoji'

**Comment by ebankoff** [comment]
Hello. **Please read the manual on how to use the software! It deals with a similar problem.** 

![image](https://user-images.githubusercontent.com/80776324/156823643-de0ee369-e33a-4d09-ac4d-afe4fffd0bed.png)

**In your case, open a terminal/cmd and write: pip install emoji**

**Comment by GurteX** [comment]
didnt kn i can just install it

**Comment by GurteX** [comment]
how many other things i have to install btw

**Comment by ebankoff** [comment]
If the software did not install the required libraries, the **requirements.txt** file contains all the libraries that must be installed, you can install them manually.

**Comment by GurteX** [comment]
ok
