### ISSUE TITLE
Getting stuck on "ERROR" when trying to get proxies, load a bomber etc

### ISSUE THREAD

**Issue by GYKgamer** [ebankoff/BoMbEr#18]
Here's an image for reference, also all pip files are updated
![image](https://user-images.githubusercontent.com/41442793/157539192-c10fcc60-f4e5-4265-b0ef-5585b2875500.png)

**Comment by ebankoff** [comment]
You entered the wrong account token. **Read the instructions in the repository.**

**Comment by ebankoff** [comment]
![image](https://user-images.githubusercontent.com/80776324/157542750-bfaa1153-7fda-4f39-88cc-0f5bbd11776c.png)

**Comment by GYKgamer** [comment]
I tried that but still get the same error
![image](https://user-images.githubusercontent.com/41442793/157546638-d4cf4892-dc53-41bd-ba83-e7f7578c59b6.png)

**Comment by ebankoff** [comment]
So check your account to make sure it works, make sure the target ID is correct (it should be in your friends list or should be on the same server as you, also the target should not have dm closed), try to enable proxy and reduce the number of messages. I will test this BoMbEr feature tomorrow and if I find any flaws, I will release an update.

**Comment by GYKgamer** [comment]
ok thanks
